// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using NUnit.Framework;

[TestFixture]

public class GUIControlTests
{
	public GUIControlTests ()
	{
	}
	//TODO test a double replace-> nothing changed, test open & close-> nothing changed
	//test init + add , removeAllchildren + getchildren-> should give null
	//test set & get relative position -> equal

}


